name: CI
on: push

jobs:
  build-check:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: contains(github.event.head_commit.message, 'skip ci') == false
        uses: actions/checkout@v1